// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0U1-jfK3LyRLxZiqUZFz8677uNcP8WoI',
    appId: '1:392437002762:android:6fb5c96f8af8525c76e5f3',
    messagingSenderId: '392437002762',
    projectId: 'dicuciin-mobile-apps',
    storageBucket: 'dicuciin-mobile-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJFIQy3ni1MAYV419pZwkaTLjZkyG3uxg',
    appId: '1:392437002762:ios:04d050d07010faec76e5f3',
    messagingSenderId: '392437002762',
    projectId: 'dicuciin-mobile-apps',
    storageBucket: 'dicuciin-mobile-apps.appspot.com',
    androidClientId: '392437002762-qmhe1j0d8tvvna6lhb1cn1mdaehhdihe.apps.googleusercontent.com',
    iosClientId: '392437002762-fh97n4c80lfdquecie9g8hvf7h8838kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.dicuciin2',
  );
}
